# Generated by Django 5.0.7 on 2024-08-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
                ('room_number', models.PositiveSmallIntegerField()),
                ('class_size', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('school_year', models.DateField()),
                ('created_at', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
